// GENERATED by tools/korea-map/build_korea_map.py. Do not edit by hand; re-run the script instead.
// Source: https://raw.githubusercontent.com/vuski/admdongkor/master/ver20260701/HangJeongDong_ver20260701.geojson
// Version: vuski/admdongkor ver20260701 (행정동 경계, 2026-07-01 기준), input SHA-256 c01ef44a0eb00978662ba7a6240ccb1da287fb52abd85104a1758969d391132f
// Licenses: 통계청 통계지리정보서비스(SGIS) 행정구역 경계 — 공공누리 제1유형(출처표시);
//           vuski/admdongkor 보정본 — CC BY 4.0 (https://creativecommons.org/licenses/by/4.0/).
// Processing: 행정동 → 시·군·구(sgg)·시·도(sido) 병합, GEOS coverage simplification, 앱 좌표 투영 (x = (lng − 124.5)·cos 36°·10000, y = (39.0 − lat)·10000).
package com.coffeejournal.domain.reference

/** 세종특별자치시: 1 시·군·구, simplified with a tolerance of 7 map units. */
internal object KoreaMapProvince36 {
    val districts: List<KoreaMapData.District> = listOf(
        KoreaMapData.District("36110", "세종시", 22468, 24879, D36110),
    )

    private const val D36110: String = "q3qBgusBTbpCVTNlCPdCZSXAnCxBfWhCO3BBf5B5BfdQCXzBB1BWdwBTqCbBRjBTA3BoCRoBIqB7BmCnCOjBmB9D8CtBaCSiBcwBESJiBkBoB4CkB-DKEQ4BNaeQgBAiBf0CI2BJOLCzCWOoB4BKiBAmCcqCSgDNcxCsCEiBlBsBX2CcsBmBWQ2CHczCgCR6EGmBoBiBgB8DL8BRMAkBO4BwBQGgBzBOvBLzBmCNmBQU-BaSeFuDAqCaDsBgBuBOwCwBuCmDaMoCT0BeGyBoBmBsBdDVqBRWQN4CP2BeoBe4BCU8BFoBdWDoCgBuByBPkCxB0BJoD7ByBfK7BFzBqDRyBrByCKmBYkBqBmBGatCEfqBjBHZdnBEnCgCHcKyBbsBG0BeSKUE2BeUoC4DDe9DiD7BsCD2BgDoCa8BI4B3BARGDmBa0BgBuB0BI2BZwCQmD8BEoDLC7BgDagDe8COa-BgCoBXkBkBOyBKgCZgClBwBlBeuB-BI4BF2ClBoBaUyCwB4BU0BECI0Cae6BwByBqBgBI4CUWefwBSEoBmCY8BGkBDiBwC0CwDUsBoDXgBVGZPhCUjBqBVyBLsBK6D4BUAwBdmBS6BL2BTChCgCBQ1BiCRyBWW1BUHUO2CHoCyBasBsBRcxBSBQW6BMkBX6CvCkDtCNjDcnBQBGjBc7CkC1BkCNuB7BsBlDNlBd5DqBXmB3BsBtBObA1BhBfRfhB7ECjBS7BQR2CasBEgBNkCnCyBvCoBpBaHgBG0BgB4B6CoBScekChByEnBInCXXB1BY1CFxBhBXd_BP9BpBX7BtBCPqCpBiBHeGqBPH3BrBzCJ1D5BzCjBGZS3CGrDTfTG1BLlCPL3BVAxBMZ7BnChBJPtB8BLBvBO9CtDa5BqB1BEjBSJUfE3DDZZdLrCFjCmBZJZ1CO3BNR1CtCvBZbfN9BrBhBrBQ3BH5DXVfxBLrBmCbzC-B1BMTKhDoBjDCdNb5BzBXnBKhDP9BzB7BvBrB1B_CFdMzDM7B5BZ9BwB7BIhBPnBjCK9BiBQQRUlCqB9CsB1CoDFcNmCzBkBtBFXC3B2B3BS_BGrDUxBCnCvBhClBP9CApCZfPVhBvBbjCG7BN_BtCrD4BrBErCFzCtBjBlBNDzBkBlBNZpBT9BxBZtB_BPlB5BflBalBRpBdZjBCpCrCIlBLlCvB1BH9BhBTVFnB"
}
