// Generated from the web app reference data by scratchpad/site/gen_refs.py. Do not edit by hand.
package com.coffeejournal.domain.reference

object Varieties {
    data class Lineage(
        val key: String,
        val type: String,
        val parents: List<String>,
        val parentNotes: List<String>,
        val symbol: String,
        val desc: String,
        val traits: List<String>,
        val note: String?,
    )

    /** lowercase raw name -> Korean label (web VARIETY_KOREAN_NAMES). */
    val koreanNames: Map<String, String> = mapOf(
        "maracaturra" to "마라카투라",
        "pache" to "파체",
        "pache comum" to "파체 코문",
        "sudan rume" to "수단 루메",
        "rume sudan" to "루메 수단",
        "jember" to "젬버",
        "wush wush" to "우쉬우쉬",
        "laurina" to "라우리나",
        "mokka" to "모카",
        "moka" to "모카",
        "san ramon" to "산라몬",
        "blue mountain" to "블루마운틴",
        "ruiru 11" to "루이루 11",
        "marsellesa" to "마르세예사",
        "obata" to "오바타",
        "icatu" to "이카투",
        "sarchimor" to "사치모르",
        "parainema" to "파라이네마",
        "costa rica 95" to "코스타리카 95",
        "ateng" to "아텡",
        "timtim" to "팀팀",
        "kents" to "켄츠",
        "kent" to "켄트",
        "s795" to "S795",
        "sln9" to "SLN9",
        "agaro" to "아가로",
        "dega" to "데가",
        "gesha" to "게이샤",
        "geisha" to "게이샤",
        "centroamericano" to "센트로아메리카노",
        "catucai" to "카투카이",
        "tekisic" to "테키식",
        "limani" to "리마니",
        "java" to "자바",
        "ihcafe90" to "IHCAFE90",
        "lempira" to "렘피라",
        "anacafe14" to "아나카페14",
        "milenio" to "밀레니오",
        "bourbon mutation" to "버번 변이종",
    )

    /** Checklist reference names "한글 (English)" (web VARIETY_REFERENCE). */
    val reference: List<String> = listOf(
        "티피카 (Typica)",
        "버번 (Bourbon)",
        "레드 버번 (Red Bourbon)",
        "핑크 버번 (Pink Bourbon)",
        "옐로 버번 (Yellow Bourbon)",
        "카투라 (Caturra)",
        "카투아이 (Catuai)",
        "게이샤 (Geisha)",
        "파카마라 (Pacamara)",
        "SL28",
        "SL34",
        "문도노보 (Mundo Novo)",
        "파카스 (Pacas)",
        "마라고지페 (Maragogype)",
        "카스티요 (Castillo)",
        "빌라사르치 (Villa Sarchi)",
        "루이루 11 (Ruiru 11)",
        "바티안 (Batian)",
        "카티모르 (Catimor)",
        "자바 (Java)",
        "파파요 (Papayo)",
        "옴블리곤 (Ombligón)",
        "치로소 (Chiroso)",
        "라우리나 (Laurina)",
        "치초 가요 (Chicho Gallo)",
        "Heirloom (에티오피아 재래종)",
    )

    val aliases: Map<String, String> = mapOf("geisha" to "gesha")

    val lineage: Map<String, Lineage> = listOf(
        Lineage("ethiopian heirloom", "재래종 집단", listOf("Ethiopian wild coffee", "Local landraces"), listOf("야생 유전자원", "지역별 오랜 선발"), "→", "에티오피아 각 지역에서 오랫동안 이어진 다양한 재래종을 넓게 묶어 부르는 이름이에요.", listOf("에티오피아", "높은 유전 다양성", "재래종 집단"), null),
        Lineage("typica", "기초 아라비카 계통", listOf("Ethiopian Arabica", "Yemen → Java"), listOf("에티오피아 기원", "이동·재배 선발"), "→", "에티오피아와 예멘을 거쳐 자바로 전해진 오래된 아라비카 계통으로, 많은 현대 품종의 바탕이 되었어요.", listOf("전통 품종", "긴 수형", "현대 품종의 기반"), null),
        Lineage("bourbon", "기초 아라비카 계통", listOf("Ethiopian Arabica", "Yemen → Bourbon Island"), listOf("에티오피아 기원", "이동·재배 선발"), "→", "예멘에서 부르봉섬으로 전해져 선발된 오래된 아라비카 계통으로, 카투라·파카스 등 여러 품종의 출발점이에요.", listOf("전통 품종", "좋은 컵 품질", "현대 품종의 기반"), null),
        Lineage("red bourbon", "Bourbon 계통", listOf("Bourbon", "Red-fruit selection"), listOf("원 품종", "붉은 열매 선발"), "→", "붉게 익는 열매를 가진 버번 계통으로, 버번의 대표적인 재배 형태예요.", listOf("Bourbon 계통", "붉은 열매"), null),
        Lineage("yellow bourbon", "Bourbon 계통", listOf("Bourbon 계통", "Yellow-fruit selection"), listOf("원 계통", "노란 열매 선발"), "→", "노랗게 익는 열매를 기준으로 선발된 버번 계통이에요.", listOf("Bourbon 계통", "노란 열매"), null),
        Lineage("villa sarchi", "자연 돌연변이", listOf("Bourbon", "Natural mutation"), listOf("원 품종", "코스타리카에서 발견"), "→", "코스타리카 빌라 사르치 지역에서 발견된 버번의 왜성 자연 돌연변이예요.", listOf("Bourbon 계통", "왜성", "코스타리카"), null),
        Lineage("pacas", "자연 돌연변이", listOf("Bourbon", "Natural mutation"), listOf("원 품종", "엘살바도르에서 발견"), "→", "엘살바도르에서 발견된 버번의 왜성 자연 돌연변이예요.", listOf("Bourbon 계통", "왜성", "엘살바도르"), null),
        Lineage("maragogype", "자연 돌연변이", listOf("Typica", "Natural mutation"), listOf("원 품종", "브라질에서 발견"), "→", "티피카에서 자연적으로 나타난 돌연변이로, 매우 큰 종자와 나무가 특징이에요.", listOf("Typica 계통", "큰 종자", "자연 돌연변이"), null),
        Lineage("catimor", "교배 품종군", listOf("Caturra", "Timor Hybrid"), listOf("Bourbon 자연 돌연변이", "Arabica × Robusta 자연교배"), "×", "카투라의 작은 수형과 티모르 하이브리드의 커피 녹병 저항성을 결합한 품종군이에요.", listOf("녹병 저항성", "소형 수형", "품종군"), "Catimor는 하나의 단일 품종이 아니라 여러 선발 계통을 묶어 부르는 이름이에요."),
        Lineage("sarchimor", "교배 품종군", listOf("Villa Sarchi", "Timor Hybrid"), listOf("Bourbon 자연 돌연변이", "Arabica × Robusta 자연교배"), "×", "빌라 사르치 계통의 수형과 티모르 하이브리드의 내병성을 결합한 품종군이에요.", listOf("녹병 저항성", "중미 육종", "품종군"), null),
        Lineage("castillo", "복합 육종 계통", listOf("Caturra", "Timor Hybrid 계통"), listOf("Bourbon 자연 돌연변이", "내병성 유전자원"), "×", "콜롬비아에서 녹병 저항성과 생산성을 목표로 여러 세대를 선발해 만든 복합 품종이에요.", listOf("콜롬비아", "녹병 저항성", "복합 선발"), "부모 둘로 끝나는 단순 교배가 아니라 여러 세대의 선발을 거친 계통이에요."),
        Lineage("caturra", "자연 돌연변이", listOf("Bourbon", "Natural mutation"), listOf("원 품종", "브라질에서 발견"), "→", "버번에서 자연적으로 나타난 왜성 돌연변이로, 작은 수형과 높은 재식 밀도가 특징이에요.", listOf("Bourbon 계통", "왜성", "자연 돌연변이"), null),
        Lineage("gesha", "재래종 · 선발", listOf("Ethiopian landrace", "Central America"), listOf("에티오피아 기원", "이동·지역 선발"), "→", "에티오피아 기원의 재래종이 중미로 이동한 뒤, 파나마에서 독특한 향미로 널리 알려진 품종이에요.", listOf("플로럴", "에티오피아 기원", "파나마에서 명성"), "Geisha와 Gesha 표기는 각 커피 기록에 적힌 원문을 그대로 유지해요."),
        Lineage("mundo novo", "자연 교배", listOf("Typica", "Bourbon"), listOf("전통 아라비카", "전통 아라비카"), "×", "브라질에서 발견된 티피카와 버번의 자연 교배 계통으로, 수세가 강하고 생산성이 높은 편이에요.", listOf("브라질", "높은 생산성", "자연 교배"), null),
        Lineage("catuai", "교배 품종", listOf("Mundo Novo", "Caturra"), listOf("Typica × Bourbon", "Bourbon 자연 돌연변이"), "×", "문도노보의 수세와 생산성에 카투라의 작은 수형을 결합하기 위해 브라질에서 개발한 품종이에요.", listOf("브라질", "소형 수형", "교배 품종"), null),
        Lineage("pacamara", "교배 품종", listOf("Pacas", "Maragogype"), listOf("Bourbon 돌연변이", "Typica 돌연변이"), "×", "파카스의 생산성과 마라고지페의 큰 종자 특성을 결합하기 위해 엘살바도르에서 개발한 품종이에요.", listOf("큰 종자", "엘살바도르", "교배 품종"), null),
        Lineage("pink bourbon", "유전적 기원 연구 중", listOf("Ethiopian landrace 계통", "지역 선발"), listOf("유전 연구 결과", "콜롬비아에서 선발"), "→", "이름과 달리 버번의 단순 변이로 단정하기 어려우며, 최근에는 에티오피아 재래종과 가까운 별도 계통으로 설명돼요.", listOf("콜롬비아", "플로럴", "기원 연구 중"), "계보가 확정되지 않은 품종은 부모를 단정하지 않고 연구 상태를 함께 표시해요."),
        Lineage("ruiru 11", "복합 교배 품종", listOf("Catimor 계통", "선발 아라비카 계통"), listOf("내병성 계통", "품질·농업 특성 선발"), "×", "케냐에서 커피베리병과 녹병 저항성을 목표로 개발한 복합 교배 품종이에요.", listOf("케냐", "내병성", "복합 교배"), null),
        Lineage("batian", "복합 육종 품종", listOf("케냐 육종 계통", "다세대 선발"), listOf("SL·Rume Sudan 계통 포함", "품질·내병성 선발"), "→", "케냐에서 컵 품질과 병 저항성을 함께 목표로 여러 계통을 교배·선발해 만든 품종이에요.", listOf("케냐", "내병성", "복합 선발"), null),
        Lineage("robusta", "커피 종", listOf("Coffea canephora", "Cultivated selections"), listOf("종 자체", "재배 선발"), "→", "아라비카와 다른 종인 코페아 카네포라로, 높은 온도에 잘 견디고 카페인과 바디가 강한 편이에요.", listOf("C. canephora", "높은 카페인", "강한 수세"), null),
        Lineage("liberica", "커피 종", listOf("Coffea liberica", "Cultivated selections"), listOf("종 자체", "재배 선발"), "→", "아라비카·로부스타와 다른 종으로, 큰 열매와 독특한 향미를 지닌 희소한 재배 커피예요.", listOf("C. liberica", "큰 열매", "희소 품종"), null),
    ).associateBy { it.key }

    val genealogyOrder: List<String> = listOf(
        "ethiopian heirloom",
        "typica",
        "bourbon",
        "gesha",
        "robusta",
        "liberica",
        "red bourbon",
        "yellow bourbon",
        "pink bourbon",
        "caturra",
        "villa sarchi",
        "pacas",
        "maragogype",
        "mundo novo",
        "catuai",
        "pacamara",
        "catimor",
        "sarchimor",
        "castillo",
        "ruiru 11",
        "batian",
    )

    val displayNames: Map<String, String> = mapOf(
        "ethiopian heirloom" to "Heirloom (에티오피아 재래종)",
        "typica" to "티피카 (Typica)",
        "bourbon" to "버번 (Bourbon)",
        "gesha" to "게이샤 (Gesha)",
        "robusta" to "로부스타 (Robusta)",
        "liberica" to "리베리카 (Liberica)",
        "red bourbon" to "레드 버번 (Red Bourbon)",
        "yellow bourbon" to "옐로 버번 (Yellow Bourbon)",
        "pink bourbon" to "핑크 버번 (Pink Bourbon)",
        "caturra" to "카투라 (Caturra)",
        "villa sarchi" to "빌라사르치 (Villa Sarchi)",
        "pacas" to "파카스 (Pacas)",
        "maragogype" to "마라고지페 (Maragogype)",
        "mundo novo" to "문도노보 (Mundo Novo)",
        "catuai" to "카투아이 (Catuai)",
        "pacamara" to "파카마라 (Pacamara)",
        "catimor" to "카티모르 (Catimor)",
        "sarchimor" to "사치모르 (Sarchimor)",
        "castillo" to "카스티요 (Castillo)",
        "ruiru 11" to "루이루 11 (Ruiru 11)",
        "batian" to "바티안 (Batian)",
    )
}
